#!/usr/bin/env python3
"""Apple boot.efi mode-switch reference: generate and verify.

    python3 tools/efiloader/ref/apple_modeswitch.py            # verify (gate)
    python3 tools/efiloader/ref/apple_modeswitch.py --regen    # re-emit the .S

The .S file is a listing of bytes copied out of a real, working loader.  A
listing is only evidence if it still matches the binary it came from, so the
default mode re-reads assets/boot.efi and compares byte-for-byte.  It also
re-checks each individual claim, because "the bytes match" and "the bytes
mean what the comment says" are different questions and either can rot alone.
"""
import os
import sys
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
BOOT_EFI = os.path.join(REPO, 'tools', 'bootlab', 'assets', 'boot.efi')
ASM_OUT = os.path.join(HERE, 'apple-boot32-modeswitch.S')

START = 0x15830
END = 0x15889            # inclusive of the trailing hlt

# Claims this script asserts, so the .S comments cannot drift from the bytes.
CLAIMS = [
    # (file offset, expected bytes, what it must be)
    (0x1584b, b'\x0f\x01\x15\x3e\x00\x00\x00', 'lgdt [rip+0x3e]'),
    (0x15852, b'\x66\xb8\x10\x00', 'mov ax,0x10'),
    (0x15856, b'\x8e\xd8', 'mov ds,eax'),
    (0x15858, b'\x8e\xc0', 'mov es,eax'),
    (0x1585a, b'\x8e\xe8', 'mov gs,eax'),
    (0x1585c, b'\x8e\xe0', 'mov fs,eax'),
    (0x15865, b'\xff\x28', 'jmp [rax]  <- NEAR indirect; cannot load CS'),
    (0x15867, b'\x0f\x20\xc0', 'mov rax,cr0'),
    (0x1586a, b'\x0f\xba\xf0\x1f', 'btr eax,0x1f  (clear CR0.PG)'),
    (0x1586e, b'\x0f\x22\xc0', 'mov cr0,rax'),
    (0x15875, b'\xb9\x80\x00\x00\xc0', 'mov ecx,0xc0000080 (IA32_EFER)'),
    (0x1587a, b'\x0f\x32', 'rdmsr'),
    (0x1587c, b'\x0f\xba\xf0\x08', 'btr eax,8  (clear EFER.LMA)'),
    (0x15880, b'\x0f\x30', 'wrmsr'),
    (0x15886, b'\xff\xe7', 'jmp rdi  (near; destination supplied by caller)'),
]

# The GDT pseudo-descriptor Apple's lgdt reads: offset 0x15890.
GDTR_OFF = 0x15890
GDTR_LIMIT = 0x0018
GDTR_BASE = 0x0

HEADER = """/*
 * Apple boot.efi -- the reference long->compat handoff, AS IT IS ON THE WIRE.
 *
 * Source: tools/bootlab/assets/boot.efi (Apple's loader, PE32+ x86-64,
 * .text va=0x1000 rptr=0x1000, so file offset == RVA).  That binary is the
 * one that actually boots this machine, which is what makes it a reference.
 *
 * GENERATED by tools/efiloader/ref/apple_modeswitch.py -- do not hand-edit.
 * Verify with:  python3 tools/efiloader/ref/apple_modeswitch.py
 *
 * WHY THIS FILE EXISTS: QemuKernelLoaderFsDxe was assumed to contain this
 * sequence.  It does not -- that module has zero lgdt, zero mov-from-CR, zero
 * mov-to-CR and zero wrmsr, verified with a positive control.  So the EDK2
 * module is not a reference for this transition, and this one is.
 *
 * READ THIS PART CAREFULLY.  The transfer at 0x15865 is
 *     ff 28    jmp qword ptr [rax]        ; NEAR indirect jump
 * A near jump NEVER loads CS.  It is therefore not the mode switch, and it is
 * NOT an alternative to a far return for leaving long mode -- no near jump
 * ever is.  What it does here is dispatch into the prep routine at 0x15867.
 * The long->compat CS change happens on some other path that this listing does
 * not contain, and locating it is the open question.
 *
 * The block 0x15830-0x15865 is 64-bit code.  Decoded in CS_MODE_32 the REX
 * prefixes change meaning ('48 8d 05 30 00 00 00' becomes
 * 'dec eax; lea eax,[0x30]'), so the RIP-relative LEAs only resolve as written
 * in 64-bit mode.
 */
"""

def load():
    if not os.path.exists(BOOT_EFI):
        print("FAIL: %s not found" % BOOT_EFI)
        sys.exit(1)
    return open(BOOT_EFI, 'rb').read()

def region(d):
    return d[START:END]

def parse_asm(path):
    """Return the byte stream declared by the .S file."""
    out = bytearray()
    for line in open(path):
        line = line.split('/*')[0]
        if '.byte' not in line:
            continue
        body = line.split('.byte', 1)[1]
        for tok in body.split(','):
            tok = tok.strip()
            if tok.startswith('0x') and len(tok) == 4:
                out.append(int(tok, 16))
    return bytes(out)

def disassemble(data, base=START):
    from capstone import Cs, CS_ARCH_X86, CS_MODE_64
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.skipdata = True
    return list(md.disasm(data, base))

def regen(d):
    lines = [HEADER, "", "\t.text", "\t.globl\tapple_modeswitch",
             "apple_modeswitch:"]
    for i in disassemble(region(d)):
        bs = ', '.join('0x%02x' % b for b in i.bytes)
        raw = ' '.join('%02x' % b for b in i.bytes)
        lines.append("\t.byte\t%-30s/* 0x%05x  %-22s %s */" % (
            bs + ',', i.address, raw, i.mnemonic + ' ' + i.op_str))
    lines += ["\t.size\tapple_modeswitch, .-apple_modeswitch", ""]
    open(ASM_OUT, 'w').write('\n'.join(lines))
    print("regenerated %s (%d bytes of code)" % (ASM_OUT, len(region(d))))

def verify(d):
    fails = []

    if not os.path.exists(ASM_OUT):
        print("FAIL: %s missing; run with --regen" % ASM_OUT)
        return 1

    # 1. The .S byte stream must equal the bytes in the real loader.
    declared = parse_asm(ASM_OUT)
    actual = region(d)
    if declared != actual:
        fails.append("byte stream differs from %s @0x%x" % (
            os.path.basename(BOOT_EFI), START))
        for i, (a, b) in enumerate(zip(declared, actual)):
            if a != b:
                fails.append("  first difference at +0x%x: asm=%02x bin=%02x" % (i, a, b))
                break

    # 2. Each specific claim must still hold in the binary.
    for off, want, what in CLAIMS:
        got = d[off:off + len(want)]
        if got != want:
            fails.append("0x%05x %-34s expected %s got %s" % (
                off, what, want.hex(' '), got.hex(' ')))

    # 3. The GDT Apple loads, read straight from the binary.
    limit = struct.unpack_from('<H', d, GDTR_OFF)[0]
    base = struct.unpack_from('<Q', d, GDTR_OFF + 2)[0]
    if limit != GDTR_LIMIT or base != GDTR_BASE:
        fails.append("GDT pseudo-descriptor @0x%x: limit=0x%04x base=0x%x "
                     "(expected limit=0x%04x base=0x%x)" % (
                         GDTR_OFF, limit, base, GDTR_LIMIT, GDTR_BASE))

    # 4. The listing must decode as one contiguous instruction stream.
    ins = disassemble(region(d))
    covered = sum(i.size for i in ins)
    if covered != len(actual):
        fails.append("instructions cover %d of %d bytes" % (covered, len(actual)))

    print("checked %s" % os.path.relpath(BOOT_EFI, REPO))
    print("  0x%05x-0x%05x  %d bytes, %d instructions" % (START, END - 1, len(actual), len(ins)))
    print("  GDT @0x%x: limit=0x%04x base=0x%x  (code at selector 0x08, data at 0x10)"
          % (GDTR_OFF, limit, base))
    print("  transfer: ff 28 = jmp [rax]  NEAR indirect -- dispatch, NOT a CS change")
    if fails:
        print("FAIL:")
        for f in fails:
            print("  " + f)
        return 1
    print("OK: listing matches Apple's boot.efi byte-for-byte, every claim holds.")
    return 0

if __name__ == '__main__':
    d = load()
    if '--regen' in sys.argv:
        regen(d)
        sys.exit(verify(d))
    sys.exit(verify(d))
