# ------------------------------------------------------------------------
#  RAVYNOS BUILD SYSTEM - Frameworks
# ------------------------------------------------------------------------

SUBDIR += CoreFoundation
#SUBDIR += CFNetwork
SUBDIR += Foundation
SUBDIR += CoreServices

Foundation: CoreFoundation

.include <bsd.subdir.mk>
