# ------------------------------------------------------------------------
#  RAVYNOS BUILD SYSTEM - Frameworks
# ------------------------------------------------------------------------

SUBDIR = CoreFoundation
#SUBDIR += CFNetwork
SUBDIR += Foundation
SUBDIR += CoreServices
SUBDIR += Onyx2D

all: ${SUBDIR}

Foundation: CoreFoundation

.include <bsd.subdir.mk>
