#!/usr/bin/env python3
"""Recompile the boot-critical xnu objects and relink the kernel.

  python3 tools/bootlab/kernel_build.py

Prerequisite: one completed full xnu build tree (default
/Users/max/Projects/build/DEVELOPMENT_X86_64, override with
RAVYN_BUILD_DIR). This script only recompiles the objects carrying ravynOS
boot fixes and relinks; it does not run the xnu Makefiles.

Outputs:
  work/new_kernel.development       linked kernel
  work/stripped_kernel.development  `strip -x` payload for mkimage.py

Templates start.s.json / i386_init.c.json are committed copies of the
original per-object compile-command JSONs (paths inside are absolute and
point at the source tree, so they are stable across machines with this repo
layout). All other recompiles clone their existing <obj>.o.json from the
build tree, which is regenerated by the real build system.
"""
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.environ.get("RAVYN_BUILD_DIR",
                           "/Users/max/Projects/build/DEVELOPMENT_X86_64")
SRC = os.environ.get("RAVYN_SRC", "/Users/max/Projects/ravynos/Kernel/xnu")
WORK = os.path.join(HERE, "work")

if not os.path.isfile(os.path.join(BUILD_DIR, ".LDFLAGS")):
    sys.exit("no full build tree at %s (set RAVYN_BUILD_DIR)" % BUILD_DIR)
os.makedirs(WORK, exist_ok=True)

osfmk_dev = os.path.join(BUILD_DIR, "osfmk", "DEVELOPMENT")
bsd_dev = os.path.join(BUILD_DIR, "bsd", "DEVELOPMENT")
with open(os.path.join(HERE, "templates", "start.s.json")) as f:
    start_cmd = json.load(f)
with open(os.path.join(HERE, "templates", "i386_init.c.json")) as f:
    init_cmd = json.load(f)

def load_json(path):
    with open(path) as f:
        return json.loads(f.read().strip().rstrip(","))

def run(args, cwd):
    subprocess.run(args, cwd=cwd, check=True)
def compile_with(template, srcfile, outfile):
    """Clone a compile command, swapping the template's source file and -o target."""
    args = list(template["arguments"])
    args[args.index(template["file"])] = srcfile
    args[args.index("-o") + 1] = outfile
    print("Compiling %s..." % os.path.basename(srcfile), flush=True)
    run(args, template["directory"])


# start.s / i386_init.c and the osfmk objects recompiled from the same
# template (they had no usable per-object json when the pipeline was built).
compile_with(start_cmd,
             os.path.join(SRC, "osfmk/x86_64/start.s"),
             os.path.join(osfmk_dev, "start.o"))
compile_with(init_cmd,
             os.path.join(SRC, "osfmk/i386/i386_init.c"),
             os.path.join(osfmk_dev, "i386_init.o"))
# (vm_fault.c intentionally NOT recompiled: the proven build cloned the
#  command but never ran it; its object stays as the full build made it.)
for rel in ["osfmk/i386/tsc.c", "osfmk/kern/startup.c", "osfmk/kern/telemetry.c",
            "osfmk/kern/zalloc.c", "osfmk/kern/bsd_kern.c",
            "osfmk/kern/kalloc.c", "osfmk/kern/sched_prim.c", "osfmk/kern/smr.c",
            "osfmk/kern/task.c",
            "osfmk/i386/mp_desc.c", "osfmk/i386/cpu_topology.c",
            "osfmk/i386/pcb_native.c", "osfmk/kern/thread_call.c",
            "osfmk/kern/mpsc_queue.c", "osfmk/kern/core_analytics.c"]:
    compile_with(init_cmd, os.path.join(SRC, rel),
                 os.path.join(osfmk_dev, os.path.basename(rel)[:-2] + ".o"))

# --------------------------------------------------- per-object json clones
# Objects whose .o.json in the build tree carries the exact right command.
for rel in ["iokit/DEVELOPMENT/IOPlatformExpert.cpo.json",
            "iokit/DEVELOPMENT/KernelConfigTables.cpo.json",
            "iokit/DEVELOPMENT/IOStartIOKit.cpo.json",
            "iokit/DEVELOPMENT/IOKitBSDInit.cpo.json",
            "iokit/DEVELOPMENT/IOPMrootDomain.cpo.json",
            "osfmk/DEVELOPMENT/commpage.o.json",
            "osfmk/DEVELOPMENT/processor.o.json",
            "osfmk/DEVELOPMENT/thread.o.json",
            "osfmk/DEVELOPMENT/i386_vm_init.o.json",
            "osfmk/DEVELOPMENT/video_console.o.json",
            "osfmk/DEVELOPMENT/vm_kern.o.json",
            "osfmk/DEVELOPMENT/ccdrbg.o.json",
            "osfmk/DEVELOPMENT/prng_random.o.json",
            "osfmk/DEVELOPMENT/vm_map.o.json",
            "osfmk/DEVELOPMENT/startup.o.json",
            "osfmk/DEVELOPMENT/thread_call.o.json",
            "osfmk/DEVELOPMENT/zalloc.o.json",
            "pexpert/DEVELOPMENT/pe_init.o.json",
            "pexpert/DEVELOPMENT/pe_serial.o.json",
            "libkern/DEVELOPMENT/corecrypto_aes.o.json",
            "libkern/DEVELOPMENT/corecrypto_md5.o.json",
            "libkern/DEVELOPMENT/corecrypto_sha2.o.json",
            "bsd/DEVELOPMENT/kern_trustcache.o.json",
            "bsd/DEVELOPMENT/vfs_init.o.json",
            "bsd/DEVELOPMENT/bsd_stubs.o.json",
            "bsd/DEVELOPMENT/pthread_shims.o.json",
            "bsd/DEVELOPMENT/bsd_init.o.json",
            "bsd/DEVELOPMENT/route.o.json",
            "bsd/DEVELOPMENT/ubc_subr.o.json",
            "bsd/DEVELOPMENT/kern_cs.o.json",
            "bsd/DEVELOPMENT/kern_mib.o.json",
            # thread_setentrypoint() lives in bsd_i386.c. Without this an edit
            # there silently produced an unchanged kernel.
            "osfmk/DEVELOPMENT/bsd_i386.o.json",
            # kern_sig.c owns the crash-reporting os_reason buffer allocation
            # (build_signal_reason). It was absent from this allowlist, so an
            # edit to that file silently produced an unchanged kernel -- a
            # green build that changed nothing, which is the exact failure
            # verify_provenance.py exists to catch.
            "bsd/DEVELOPMENT/kern_sig.o.json",
            # wait4/proc_exit live in kern_exit.c. Without this an edit there
            # silently produced an unchanged kernel.
            "bsd/DEVELOPMENT/kern_exit.o.json",
            # fork()/vfork() syscall entry points live in kern_fork.c.
            # Without this an edit there silently produced an unchanged
            # kernel, and syscall 66 stayed nosys().
            "bsd/DEVELOPMENT/kern_fork.o.json",
            # fork1() calls kern_protect()/proc_* helpers; keep it in step
            # with kern_fork.c.
            "bsd/DEVELOPMENT/kern_prot.o.json",
            # mig_init() builds the MIG dispatch table in ipc_kobject.c.
            # Without this the descriptor-stride fix never reached the
            # kernel, so mig_table_max_displ stayed at its broken value.
            "osfmk/DEVELOPMENT/ipc_kobject.o.json",
            # init_sysent.c is the syscall dispatch table; without this a
            # syscalls.master edit (e.g. enabling vfork on slot 66) never
            # reached the kernel.
            "bsd/DEVELOPMENT/init_sysent.o.json",
            # model_dep.c holds efi_init()/efi_set_tables_64(). Without this
            # an edit there silently produced an unchanged kernel.
            "osfmk/DEVELOPMENT/model_dep.o.json",
            # /dev/console lives entirely in these six objects: devfs_vfsops
            # creates the node, devfs_tree/devfs_vnops resolve it to a vnode,
            # spec_vnops dispatches VCHR opens, cons.c is the major-0 console
            # driver and km.c is the tty it forwards to. Without them an edit
            # to any of them silently produced an unchanged kernel.
            "bsd/DEVELOPMENT/devfs_vfsops.o.json",
            "bsd/DEVELOPMENT/devfs_vnops.o.json",
            "bsd/DEVELOPMENT/devfs_tree.o.json",
            "bsd/DEVELOPMENT/spec_vnops.o.json",
            "bsd/DEVELOPMENT/cons.o.json",
            "bsd/DEVELOPMENT/km.o.json"]:
    cmd = load_json(os.path.join(BUILD_DIR, rel))
    print("Compiling %s..." % os.path.basename(rel).rsplit(".", 3)[0], flush=True)
    run(cmd["arguments"], cmd["directory"])

# --------------------------------------------------------------- BSD clones
# pthread_builtin.c and ahci_block.c are not in the stock build filelists,
# so clone bsd_stubs.o.json and swap the source (ahci adds one -I).
stubs = load_json(os.path.join(bsd_dev, "bsd_stubs.o.json"))
compile_with(stubs, os.path.join(SRC, "bsd/pthread/pthread_builtin.c"),
             os.path.join(bsd_dev, "pthread_builtin.o"))
args_ahci = list(stubs["arguments"])
args_ahci[args_ahci.index(stubs["file"])] = os.path.join(SRC, "bsd/dev/i386/ahci_block.c")
args_ahci[args_ahci.index("-o") + 1] = os.path.join(bsd_dev, "ahci_block.o")
args_ahci.append("-I" + os.path.join(SRC, "osfmk"))
print("Compiling ahci_block.c...", flush=True)
run(args_ahci, stubs["directory"])

# bsd/dev/fb0.c is likewise not in the stock filelists (the real bsd/conf/files
# entry only takes effect on a full Makefile-driven build, which this script
# does not run).  Clone bsd_stubs.o.json the same way.  The extra -I is for
# <machine/memory_types.h>, which vm/memory_types.h pulls in to define
# VM_WIMG_IO -- without it the framebuffer mapping cannot be made uncached.
args_fb0 = list(stubs["arguments"])
args_fb0[args_fb0.index(stubs["file"])] = os.path.join(SRC, "bsd/dev/fb0.c")
args_fb0[args_fb0.index("-o") + 1] = os.path.join(bsd_dev, "fb0.o")
args_fb0.append("-I" + os.path.join(SRC, "osfmk/i386"))
print("Compiling fb0.c...", flush=True)
run(args_fb0, stubs["directory"])

# kern_mman.c gains the character-device mmap dispatch that calls fb0's d_mmap,
# so it must be recompiled too -- it is in the stock filelist, hence it does
# have a per-object json to clone.
print("Compiling kern_mman.c...", flush=True)
run(load_json(os.path.join(bsd_dev, "kern_mman.o.json"))["arguments"],
    stubs["directory"])

# bsd_init.c calls fb0_init().
print("Compiling bsd_init.c...", flush=True)
run(load_json(os.path.join(bsd_dev, "bsd_init.o.json"))["arguments"],
    stubs["directory"])

# ------------------------------------------------- pthread kext (statically)
# The pthread kext (Kernel/Extensions/pthread, com.apple.kec.pthread) is not
# in the stock filelists and is never built by the xnu Makefiles, so there is
# no per-object .o.json for kern_support.c / kern_synch.c.  Clone
# bsd_stubs.o.json the same way the two BSD clones above do, then add the
# kext's own include roots and CFLAGS (from Kernel/Extensions/pthread/makefile).
# kern_init.c is deliberately not compiled: it defines pthread_kern, which
# bsd/pthread/pthread_shims.c already owns, and the kxld-only
# pthread_start/pthread_stop entry points.  bsd/pthread/pthread_builtin.c is
# the registrar in its place.
pthread_kext = os.path.abspath(os.path.join(SRC, "..", "Extensions", "pthread"))
pthread_kext_incs = [
    "-I" + os.path.join(pthread_kext, "kern"),
    "-I" + pthread_kext,
    "-I" + os.path.join(pthread_kext, "..", "..", "Libraries", "Libsystem"),
    "-I" + os.path.join(pthread_kext, "..", "..", "Libraries", "Libsystem", "private"),
]
pthread_kext_defs = ["-D__PTHREAD_EXPOSE_INTERNALS__",
                     "-DABSOLUTETIME_SCALAR_TYPE",
                     "-DNEEDS_SCHED_CALL_T",
                     "-D__STDC_HOSTED__=0"]
for name in ["kern_support.c", "kern_synch.c"]:
    args_kx = list(stubs["arguments"])
    args_kx[args_kx.index(stubs["file"])] = os.path.join(pthread_kext, name)
    # NOT "kern_synch.o": bsd/kern/kern_synch.c owns that object name in the
    # same build directory, and the plain name silently overwrote it.
    args_kx[args_kx.index("-o") + 1] = os.path.join(bsd_dev, "pthread_kext_" + name[:-2] + ".o")
    # Joined -I<dir> form on purpose: inserting a separate argument in the
    # middle of the template's existing -I/'-I <dir>' pair orphans <dir> as a
    # stray positional input, which clang reports as the very misleading
    # "cannot specify -o when generating multiple output files".
    args_kx += pthread_kext_incs + pthread_kext_defs
    print("Compiling %s..." % name, flush=True)
    run(args_kx, stubs["directory"])

# ------------------------------------------------------------------ msdosfs
print("Compiling msdosfs objects...", flush=True)
run([os.path.join(HERE, "msdosfs_compile.sh")], HERE)

# ------------------------------------------------- MIG kernel-server stubs
# The *_server.c files are produced by `mig`, and the layout of the routine
# descriptor array that mig_init() (osfmk/kern/ipc_kobject.c) walks depends
# on whether mig ran with -DKERNEL_SERVER=1:
#
#   without it -> "struct routine_descriptor routine[N]"  (40 bytes/entry,
#                 has an arg_descr pointer, no reply_descr_count)
#   with it    -> "struct kern_routine_descriptor kroutine[N]" (32 bytes/entry)
#
# mig_init() casts each subsystem to struct mig_kern_subsystem and reads
# kstub_routine/max_reply_msg/reply_descr_count, i.e. the 32-byte kernel
# layout.  When the generated tables carry the 40-byte user layout, every
# msgh_id past the first is read at the wrong offset: routines get
# misrouted, and ids that land on a zero field register nothing at all.
# Those come back as "ipc_kobject_server: bogus kernel message, id=<n>"
# and MIG_BAD_ID (-303 / 0xfffffed1) -- which is exactly how
# host_get_clock_service (mach_host 200+6 = 206) and semaphore_create
# (task 3400+18 = 3418) fail on this kernel.
#
# The checked-in generated sources were produced without -DKERNEL_SERVER=1,
# and their timestamps are newer than the .defs files, so make never
# regenerates them.  Regenerate them here with the kernel flags
# (makedefs/MakeInc.def: MIGKSFLAGS) and recompile, so the tables match
# what mig_init() reads.
MIGKSFLAGS = ["-DMACH_KERNEL_PRIVATE", "-DKERNEL_SERVER=1", "-mach_msg2"]
MIGDEFS_DIRS = [os.path.join(SRC, "osfmk", "mach"),
                os.path.join(SRC, "osfmk", "device")]

def mig_flags_from(json_path):
    """Reuse the exact -D/-I set the object was built with (i.e. MIGFLAGS)."""
    args = load_json(json_path)["arguments"]
    out, i = [], 0
    while i < len(args):
        a = args[i]
        if a == "-D":
            out.append("-D" + args[i + 1]); i += 2; continue
        if a == "-I":
            out.append("-I" + args[i + 1]); i += 2; continue
        if a.startswith("-D") and len(a) > 2:
            out.append(a); i += 1; continue
        if a.startswith("-I") and len(a) > 2:
            out.append(a); i += 1; continue
        i += 1
    return out + ["-arch", "x86_64", "-fsigned-bitfields", "-novouchers"]

server_jsons = sorted(glob.glob(os.path.join(osfmk_dev, "*_server.o.json")))
if not server_jsons:
    sys.exit("no MIG server objects found in %s" % osfmk_dev)
for jpath in server_jsons:
    base = os.path.basename(jpath)[:-len(".o.json")]
    rel_c = load_json(jpath)["file"]              # e.g. mach/mach_host_server.c
    c_path = os.path.join(osfmk_dev, rel_c)
    h_path = os.path.splitext(c_path)[0] + ".h"
    stem = base[:-len("_server")]                 # e.g. mach_host
    defs = None
    for dd in MIGDEFS_DIRS:
        cand = os.path.join(dd, stem + ".defs")
        if os.path.isfile(cand):
            defs = cand
            break
    if defs is None:
        sys.exit("no .defs found for %s (looked in %s)" % (base, MIGDEFS_DIRS))
    print("Regenerating MIG kernel server %s from %s..."
          % (rel_c, os.path.relpath(defs, SRC)), flush=True)
    run(["mig", "-q"] + mig_flags_from(jpath) + MIGKSFLAGS + [
        "-user", "/dev/null", "-header", "/dev/null",
        "-server", c_path, "-sheader", h_path, defs], osfmk_dev)
    print("Compiling %s..." % base, flush=True)
    run(load_json(jpath)["arguments"], load_json(jpath)["directory"])

# --------------------------------------------------------------------- link
components = ["osfmk", "bsd", "iokit", "libkern", "libsa", "pexpert",
              "security", "san"]
all_objs = []
for c in components:
    fl = os.path.join(BUILD_DIR, c, "DEVELOPMENT", "%s.filelist" % c)
    if os.path.exists(fl):
        with open(fl) as f:
            all_objs += [l.strip() for l in f if l.strip()]
with open(os.path.join(BUILD_DIR, "link.filelist"), "w") as f:
    for obj in all_objs:
        f.write(obj + "\n")

with open(os.path.join(BUILD_DIR, ".LDFLAGS"), "rb") as f:
    ldflags = f.read().replace(b"\x00", b"").decode("utf-8").strip()

out_kernel = os.path.join(WORK, "new_kernel.development")
msdosfs_objs = sorted(glob.glob(os.path.join(WORK, "msdosfs_objs", "msdosfs_*.o")))
if not msdosfs_objs:
    sys.exit("no msdosfs objects")

link_map = os.path.join(WORK, "kernel_link.map")

full_cmd = ldflags.split() + [
    "-filelist", os.path.join(BUILD_DIR, "link.filelist"),
    os.path.join(BUILD_DIR, "version.o"),
    os.path.join(BUILD_DIR, "lastkerneldataconst.o"),
    os.path.join(BUILD_DIR, "lastkernelconstructor.o"),
    os.path.join(BUILD_DIR, "nonlto.o"),
    os.path.join(BUILD_DIR, "ubsan_stubs.o"),
    os.path.join(bsd_dev, "pthread_builtin.o"),
    os.path.join(bsd_dev, "pthread_kext_kern_support.o"),
    os.path.join(bsd_dev, "pthread_kext_kern_synch.o"),
    os.path.join(bsd_dev, "ahci_block.o"),
    os.path.join(bsd_dev, "fb0.o"),
] + msdosfs_objs + ["-Wl,-map," + link_map, "-o", out_kernel]
print("Linking %s..." % out_kernel, flush=True)
run(full_cmd, BUILD_DIR)

stripped = os.path.join(WORK, "stripped_kernel.development")
run(["strip", "-x", "-o", stripped, out_kernel], WORK)
print("done: %s (%d bytes) / %s (%d bytes)" % (
    out_kernel, os.path.getsize(out_kernel),
    stripped, os.path.getsize(stripped)))
