#!/bin/bash
# Compile msdosfs sources for in-kernel linking.
# Flags cloned from bsd/DEVELOPMENT/bsd_stubs.o.json (kernel DEVELOPMENT build).
set -e
cd /Users/max/Projects/build/DEVELOPMENT_X86_64/bsd/DEVELOPMENT
CC=/Library/Developer/CommandLineTools/usr/bin/clang
OUTDIR="$(cd "$(dirname "$0")" && pwd)/work/msdosfs_objs"
SRCDIR=/Users/max/Projects/ravynos/Kernel/Extensions/msdosfs/msdosfs.kextproj/msdosfs.kmodproj
mkdir -p "$OUTDIR"
BASEFLAGS=(
  -xc
  -c
  -g
  -nostdlibinc
  -ferror-limit=10000
  -fno-builtin
  -fno-common
  -ftrivial-auto-var-init=zero
  -fsigned-bitfields
  -fmerge-all-constants
  -fc++-static-destructors=none
  -arch
  x86_64
  -D
  x86_64
  -D
  X86_64
  -D
  __X86_64__
  -D
  LP64
  -D
  PAGE_SIZE_FIXED
  -mkernel
  -static
  -msoft-float
  -D
  KERNEL_BASE_OFFSET=0x100000
  -O2
  -mmacos-version-min=15.0
  -D
  XNU_TARGET_OS_OSX
  -D
  XNU_PLATFORM_MacOSX
  -D
  APPLE
  -D
  KERNEL
  -D
  KERNEL_PRIVATE
  -D
  XNU_KERNEL_PRIVATE
  -D
  PRIVATE
  -D
  __MACHO__=1
  -D
  volatile=__volatile
  -D
  XNU_KERN_EVENT_DATA_IS_VLA
  -D
  CURRENT_MACHINE_CONFIG_LC=none
  -D
  MACH
  -D
  AH_ALL_CRYPTO
  -D
  TRAFFIC_MGT
  -D
  MULTICAST
  -D
  IFNET_INPUT_SANITY_CHK
  -D
  PSYNCH
  -D
  FLOW_DIVERT
  -D
  NECP
  -D
  CONTENT_FILTER
  -D
  PACKET_MANGLER
  -D
  CONFIG_MBUF_MCACHE
  -D
  CONFIG_MBUF_JUMBO
  -D
  CONFIG_IMAGEBOOT_CHUNKLIST
  -D
  NULLFS
  -D
  BINDFS
  -D
  CONFIG_DEV_KMEM
  -D
  NAMEDSTREAMS
  -D
  CONFIG_APPLEDOUBLE
  -D
  CONFIG_VOLFS
  -D
  CONFIG_IMGSRC_ACCESS
  -D
  CONFIG_EXT_RESOLVER
  -D
  CONFIG_SEARCHFS
  -D
  CONFIG_MNT_SUID
  -D
  CONFIG_MNT_ROOTSNAP
  -D
  CONFIG_ROSV_STARTUP
  -D
  CONFIG_FIRMLINKS
  -D
  CONFIG_MOUNT_VM
  -D
  CONFIG_MOUNT_PREBOOTRECOVERY
  -D
  CONFIG_DATALESS_FILES
  -D
  CONFIG_BASESYSTEMROOT
  -D
  CONFIG_UNION_MOUNTS
  -D
  CONFIG_FILE_LEASES
  -D
  CONFIG_IOCOUNT_TRACE
  -D
  NFSSERVER
  -D
  CONFIG_NETBOOT
  -D
  IPSEC
  -D
  IPSEC_ESP
  -D
  CRYPTO_SHA2
  -D
  ENCRYPTED_SWAP
  -D
  CONFIG_IMG4
  -D
  CONFIG_KN_HASHSIZE=64
  -D
  CONFIG_VNODES=263168
  -D
  CONFIG_NC_HASH=4096
  -D
  CONFIG_VFS_NAMES=4096
  -D
  CONFIG_MAX_CLUSTERS=8
  -D
  CONFIG_MIN_NBUF=256
  -D
  CONFIG_MIN_NIOBUF=128
  -D
  'CONFIG_NMBCLUSTERS=((1024 * 512) / MCLBYTES)'
  -D
  CONFIG_TCBHASHSIZE=4096
  -D
  CONFIG_AIO_MAX=90
  -D
  CONFIG_AIO_PROCESS_MAX=16
  -D
  CONFIG_AIO_THREAD_COUNT=4
  -D
  CONFIG_MAXVIFS=32
  -D
  CONFIG_MFCTBLSIZ=256
  -D
  CONFIG_MSG_BSIZE_REL=131072
  -D
  CONFIG_MSG_BSIZE_DEV=131072
  -D
  CONFIG_MSG_BSIZE=CONFIG_MSG_BSIZE_DEV
  -D
  CONFIG_IPC_TABLE_ENTRIES_SIZE_MAX=7340032
  -D
  CONFIG_IPC_TABLE_REQUEST_SIZE_MAX=2097152
  -D
  CONFIG_IPC_KERNEL_MAP_SIZE=64
  -D
  CONFIG_VSPRINTF
  -D
  CONFIG_DYNAMIC_CODE_SIGNING
  -D
  CONFIG_CODE_DECRYPTION
  -D
  CONFIG_PROTECT
  -D
  CONFIG_KEYPAGE_WP
  -D
  CONFIG_MEMORYSTATUS
  -D
  CONFIG_DEFERRED_RECLAIM
  -D
  CONFIG_PHYS_WRITE_ACCT
  -D
  VM_PRESSURE_EVENTS
  -D
  CONFIG_LEDGER_INTERVAL_MAX
  -D
  CONFIG_IOSCHED
  -D
  IMPORTANCE_TRACE
  -D
  CONFIG_TELEMETRY
  -D
  CONFIG_PROC_UUID_POLICY
  -D
  CONFIG_COREDUMP
  -D
  CONFIG_VNGUARD
  -D
  CONFIG_PV_TICKET
  -D
  HIBERNATION
  -D
  IOKITCPP
  -D
  IOKITSTATS
  -D
  IOTRACKING
  -D
  CONFIG_SLEEP
  -D
  CONFIG_MAX_THREADS=500
  -D
  LIBKERNCPP
  -D
  CONFIG_BLOCKS
  -D
  CONFIG_KEC_FIPS
  -D
  CONFIG_KEXT_BASEMENT
  -D
  CONFIG_PERSONAS
  -D
  CONFIG_MACF_SOCKET_SUBSET
  -D
  CONFIG_ARCADE
  -D
  CONFIG_SETUID
  -D
  CONFIG_KAS_INFO
  -D
  CONFIG_PROC_RESOURCE_LIMITS
  -D
  CONFIG_ZLEAKS
  -D
  CONFIG_VOUCHER_DEPRECATED
  -D
  LOCK_STATS
  -D
  KPERF
  -D
  CONFIG_PERVASIVE_CPI
  -D
  CONFIG_IOTRACE
  -D
  PGO
  -D
  DEVELOPMENT
  -D
  MACH_BSD
  -D
  IOKIT
  -D
  CONFIG_THREAD_MAX=2560
  -D
  CONFIG_TASK_MAX=1024
  -D
  CONFIG_ZONE_MAP_MIN=120586240
  -D
  CONFIG_SCHED_TIMESHARE_CORE
  -D
  CONFIG_SCHED_SFI
  -D
  CONFIG_PROB_GZALLOC
  -D
  MACH_KDP
  -D
  CONFIG_SERIAL_KDP
  -D
  CONFIG_KDP_INTERACTIVE_DEBUGGING
  -D
  CONFIG_KDP_COREDUMP_ENCRYPTION
  -D
  CONFIG_TASKWATCH
  -D
  CONFIG_USER_NOTIFICATION
  -D
  CONFIG_XNUPOST
  -D
  PROC_REF_DEBUG
  -D
  CONFIG_ATM
  -D
  CONFIG_COALITIONS
  -D
  CONFIG_SYSDIAGNOSE
  -D
  CONFIG_CSR
  -D
  SERIAL_CONSOLE
  -D
  VIDEO_CONSOLE
  -D
  CONFIG_REQUIRES_U32_MUNGING
  -D
  COPYOUT_SHIM
  -D
  CONFIG_MACH_BRIDGE_SEND_TIME
  -D
  CONFIG_SERVICE_PORT_INFO
  -D
  CONFIG_DELAY_IDLE_SLEEP
  -D
  CONFIG_PROC_UDATA_STORAGE
  -D
  CONFIG_TASK_SUSPEND_STATS
  -D
  PAL_I386
  -D
  CONFIG_MCA
  -D
  CONFIG_VMX
  -D
  CONFIG_MTRR
  -D
  CONFIG_MACF_LAZY_VNODE_LABELS
  -D
  HYPERVISOR
  -D
  CONFIG_MACH_APPROXIMATE_TIME
  -include
  meta_features.h
  -D
  DRIVER_PRIVATE
  -D
  _KERNEL_BUILD
  -D
  KERNEL_BUILD
  -D
  MACH_KERNEL
  -D
  BSD_BUILD
  -D
  BSD_KERNEL_PRIVATE
  -Warray-bounds-pointer-arithmetic
  -Weverything
  -Wundef-prefix=TARGET_OS_
  -Wundef-prefix=LCK_GRP_USE_ARG
  -Wno-pedantic
  -Wno-bad-function-cast
  -Wno-bitwise-instead-of-logical
  -Wno-c++-compat
  -Wno-c++98-compat
  -Wno-conditional-uninitialized
  -Wno-covered-switch-default
  -Wno-disabled-macro-expansion
  -Wno-documentation-unknown-command
  -Wno-extra-semi-stmt
  -Wno-format-non-iso
  -Wno-language-extension-token
  -Wno-missing-variable-declarations
  -Wno-packed
  -Wno-padded
  -Wno-partial-availability
  -Wno-reserved-id-macro
  -Wno-shift-sign-overflow
  -Wno-switch-enum
  -Wno-unaligned-access
  -Wno-undef
  -Wno-invalid-offsetof
  -Wno-unused-macros
  -Wno-used-but-marked-unused
  -Wno-variadic-macros
  -Wno-zero-length-array
  -Wno-packed
  -Wno-cast-function-type-strict
  -Wno-incompatible-function-pointer-types-strict
  -Wno-unknown-warning-option
  -Wno-anon-enum-enum-conversion
  -Wno-error=enum-enum-conversion
  -Wno-error=c99-designator
  -Wno-error=reorder-init-list
  -Wno-error=switch-default
  -Wno-deprecated-volatile
  -Wno-error=incompatible-function-pointer-types-strict
  -Wno-cast-function-type-strict
  -Wno-declaration-after-statement
  -Wno-sign-compare
  -Wno-sign-conversion
  -Wpointer-arith
  -Wxnu-typed-allocators
  -Wno-sign-conversion
  -I
  .
  -I
  /Users/max/Projects/ravynos/Kernel/xnu/bsd
  -I
  /Users/max/Projects/build/EXPORT_HDRS/bsd
  -I
  /Users/max/Projects/build/EXPORT_HDRS/osfmk
  -I
  /Users/max/Projects/build/EXPORT_HDRS/libkern
  -I
  /Users/max/Projects/build/EXPORT_HDRS/iokit
  -I
  /Users/max/Projects/build/EXPORT_HDRS/pexpert
  -I
  /Users/max/Projects/build/EXPORT_HDRS/security
  -I
  /Users/max/Projects/build/EXPORT_HDRS/san
  -I
  /Users/max/Projects/ravynos/Kernel/xnu/EXTERNAL_HEADERS
  -Wno-elaborated-enum-base
  -Xclang
  -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation
  -Xclang
  -fno-odr-hash-protocols
  -Xclang
  -clang-vendor-feature=+enableAggressiveVLAFolding
  -Xclang
  -clang-vendor-feature=+revert09abecef7bbf
  -Xclang
  -clang-vendor-feature=+thisNoAlignAttr
  -Xclang
  -clang-vendor-feature=+thisNoNullAttr
  -Xclang
  -clang-vendor-feature=+disableAtImportPrivateFrameworkInImplementationError
  -Xclang
  -Wno-error=allocator-wrappers
  -mlinker-version=1267
  -m64
  --target=x86_64-apple-macosx15.0.0
)
SHIMS=(-DMSDOSFS_AUTO_UNLOAD=0 -DOSMalloc=OSMalloc_external -DOSFree=OSFree_external -DOSMalloc_Tagalloc=OSMalloc_Tagalloc_external -DOSMalloc_Tagfree=OSMalloc_Tagfree_external -D_MALLOC=_MALLOC_external -D_FREE=_FREE_external)

"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_conv.c" -o "$OUTDIR/msdosfs_conv.o" -c
echo "built $OUTDIR/msdosfs_conv.o"
"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_denode.c" -o "$OUTDIR/msdosfs_denode.o" -c
echo "built $OUTDIR/msdosfs_denode.o"
"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_fat.c" -o "$OUTDIR/msdosfs_fat.o" -c
echo "built $OUTDIR/msdosfs_fat.o"
"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_lookup.c" -o "$OUTDIR/msdosfs_lookup.o" -c
echo "built $OUTDIR/msdosfs_lookup.o"
"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_vfsops.c" -o "$OUTDIR/msdosfs_vfsops.o" -c
echo "built $OUTDIR/msdosfs_vfsops.o"
"$CC" "${BASEFLAGS[@]}" "${SHIMS[@]}" -I "$SRCDIR" "$SRCDIR/msdosfs_vnops.c" -o "$OUTDIR/msdosfs_vnops.o" -c
echo "built $OUTDIR/msdosfs_vnops.o"
