/* TRAP stubs: SIGILL if any ObjC runtime fn is actually called. */
unsigned long OBJC_CLASS_$_NSObject = 0;
unsigned long OBJC_METACLASS_$_NSObject = 0;
unsigned long _objc_empty_cache = 0;
unsigned long _objc_debug_taggedpointer_mask = 0;
unsigned long _objc_debug_taggedpointer_obfuscator = 0;
void _objc_init(void) {}
void _objc_registerTaggedPointerClass(void) { __builtin_trap(); }
void __objc_personality_v0(void) { __builtin_trap(); }
void class_createInstance(void) { __builtin_trap(); }
void class_getInstanceSize(void) { __builtin_trap(); }
void class_getName(void) { __builtin_trap(); }
void objc_alloc(void) { __builtin_trap(); }
void objc_alloc_init(void) { __builtin_trap(); }
void objc_autoreleasePoolPop(void) { __builtin_trap(); }
void objc_autoreleasePoolPush(void) { __builtin_trap(); }
void objc_autoreleaseReturnValue(void) { __builtin_trap(); }
void objc_begin_catch(void) { __builtin_trap(); }
void objc_constructInstance(void) { __builtin_trap(); }
void objc_copyWeak(void) { __builtin_trap(); }
void objc_destroyWeak(void) { __builtin_trap(); }
void objc_destructInstance(void) { __builtin_trap(); }
void objc_end_catch(void) { __builtin_trap(); }
void objc_getClass(void) { __builtin_trap(); }
void objc_loadWeakRetained(void) { __builtin_trap(); }
void objc_lookUpClass(void) { __builtin_trap(); }
void objc_msgSend(void) { __builtin_trap(); }
void objc_msgSendSuper2(void) { __builtin_trap(); }
void objc_opt_class(void) { __builtin_trap(); }
void objc_opt_isKindOfClass(void) { __builtin_trap(); }
void objc_opt_respondsToSelector(void) { __builtin_trap(); }
void objc_release(void) { __builtin_trap(); }
void objc_retain(void) { __builtin_trap(); }
void objc_retainAutorelease(void) { __builtin_trap(); }
void objc_retainAutoreleasedReturnValue(void) { __builtin_trap(); }
void objc_retainBlock(void) { __builtin_trap(); }
void objc_storeWeak(void) { __builtin_trap(); }
void objc_terminate(void) { __builtin_trap(); }
void object_getClass(void) { __builtin_trap(); }
void object_getClassName(void) { __builtin_trap(); }
void object_isClass(void) { __builtin_trap(); }
void sel_registerName(void) { __builtin_trap(); }
