/*
 * Copyright (c) 2008 Johannes Fortmann
 * Copyright (c) 2026 Zoe Knox.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


#import <Foundation/NSString.h>
#include "NSCFString.h"

// This is a string type generated by gcc on OS X. The layout is that of NSCFString.
// NSInitializeProcess assigns this to __CFConstantStringClassReference.
// The flags specify the encoding etc., but we ignore them for now.

@interface NSDarwinString : NSCFString {
}

NSString *NSDarwinStringNewWithCharacters(NSZone *zone, const unichar *characters, NSUInteger length, BOOL lossy);
NSString *NSDarwinStringNewWithBytes(NSZone *zone, const char *bytes, NSUInteger length);

- (const char *)_fastCStringContents:(BOOL)getContents;
@end
