#ifndef _TARGETCONDITIONALS_H_
#define _TARGETCONDITIONALS_H_

#define TARGET_OS_OSX 1
#define TARGET_OS_MAC 1
#define TARGET_OS_IPHONE 0
#define TARGET_OS_IOS 0
#define TARGET_OS_WATCH 0
#define TARGET_OS_TV 0
#define TARGET_OS_BRIDGE 0
#define TARGET_OS_MACCATALYST 0
#define TARGET_OS_DRIVERKIT 0

#define TARGET_CPU_X86_64 1
#define TARGET_CPU_ARM64 0

#endif /* _TARGETCONDITIONALS_H_ */
