FRAMEWORK=ApplicationServices
.include "../framework.common.mk"

# Placeholder for future implementation.
# ApplicationServices is not yet implemented in ravynOS. SRCS is empty
# because there are no source files yet; it should eventually list the
# implementation files for CoreGraphics, CoreText, and other
# ApplicationServices sub-frameworks.
SRCS=
INCS=ApplicationServices.h 

RESOURCES=Info.plist

.include <rvn.framework.mk>

installresources: alt_install_hook
