
add_library(log_IOHIDFamily STATIC
	./log_IOHIDFamily/log_IOHIDFamily.m
)

add_library(HIDDisplay STATIC
	./HIDDisplay/HIDDisplayDeviceManagementCAPI.m
	./HIDDisplay/HIDDisplayInterface.m
	./HIDDisplay/HIDDisplayDeviceManagementInterface.m
	./HIDDisplay/HIDDisplayPresetInterface.m
	./HIDDisplay/HIDDisplayIOReportingInterface.m
	./HIDDisplay/HIDDisplayPresetData.m
	./HIDDisplay/HIDDisplayUserAdjustmentInterface.m
	./HIDDisplay/HIDDisplayPrivate.m
	./HIDDisplay/HIDDisplayIOReportingCAPI.m
	./HIDDisplay/HIDDisplayUserAdjustmentCAPI.m
	./HIDDisplay/HIDDisplayPresetCAPI.m
)

add_library(HIDAnalytics STATIC
	./HIDAnalytics/HIDAnalyticsHistogramEvent.m
	./HIDAnalytics/HIDAnalyticsReporter.m
	./HIDAnalytics/HIDAnalyticsEventField.m
	./HIDAnalytics/HIDAnalyticsEvent.m
	./HIDAnalytics/HIDAnalyticsCAPI.m
	./HIDAnalytics/HIDAnalyticsHistogramEventField.m
)

add_library(IOHIDFamily STATIC
	./HIDDriverKit/IOHIDDevice.iig
	./HIDDriverKit/IOHIDEventService.iig
	./IOHIDFamily/IOHIDUserDevice.cpp
	./IOHIDFamily/AppleUserHIDDevice.cpp
	./IOHIDFamily/IOHIDEventServiceFastPathUserClient.cpp
	./IOHIDSystem/IOHIDKeyboardEventDevice.cpp
	./IOHIDFamily/IOHIDEventServiceUserClient.cpp
	./IOHIDFamily/IOHIDLibUserClient.cpp
	./HIDDriverKit/IOHIDDevice.cpp
	./IOHIDFamily/IOHIDEventQueue.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtonCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetCollectionNodes.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetValueCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDHasUsage.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDMaxUsageListLength.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDNextItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDOpenCloseDescriptor.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDParseDescriptor.c
	./HIDDriverKit/IOHIDElementContainer.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessCollection.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessGlobalItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessLocalItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessMainItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessReportItem.c
	./IOHIDFamily/AppleUserHIDEventService.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageInRange.c
	./IOHIDFamily/IOHIDDeviceElementContainer.cpp
	./IOHIDSystem/IOHIDDescriptorParser/PoolAlloc.c
	./IOHIDSystem/IOHIDevice.cpp
	./IOHIDSystem/IOHIDIO.cpp
	./HIDDriverKit/IOHIDElementPrivate.cpp
	./HIDDriverKit/IOHIDInterface.cpp
	./HIDDriverKit/IOHIDInterface.iig
	./HIDDriverKit/IOHIDEventService.cpp
	./IOHIDFamily/IOHIDActionQueue.cpp
	./IOHIDFamily/IOHIDProviderPropertyMerger.cpp
	./IOHIDFamily/IOHIDEventDriver.cpp
	./IOHIDFamily/AppleEmbeddedKeyboard.cpp
	./IOHIDFamily/IOHIDEventRepairDriver.cpp
	./IOHIDFamily/IOHIDFamilyPrivate.cpp
	./HIDDriverKit/IOHIDEvent.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDCountDescriptorItems.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetReportLength.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDIsButtonOrValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDCheckReport.c
	./IOHIDFamily/IOHIDEventSource.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtonsOnPage.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtons.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetUsageValueArray.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetNextUsageValueInfo.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetNextButtonInfo.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetData.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDInitReport.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDPostProcessRIValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDPutData.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDScaleUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageListDifference.c
	./IOHIDSystem/IOHIDPointingEventDevice.cpp
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageAndPageFromIndex.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetUsageValueArray.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetScaledUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetButtons.c
	./IOHIDFamily/Cosmo_USB2ADB.c
	./IOHIDFamily/IOHIDConsumer.cpp
	./IOHIDFamily/IOHIDKeyboard.cpp
	./IOHIDFamily/IOHIDPointing.cpp
	./IOHIDSystem/IOHIDPrivate.cpp
	./IOHIDSystem/IOHIDPointingDevice.cpp
	./IOHIDSystem/IOHIDKeyboardDevice.cpp
	./IOHIDSystem/IOHIDSystem.cpp
	./IOHIDSystem/IOHIKeyboard.cpp
	./IOHIDSystem/IOHIKeyboardMapper.cpp
	./IOHIDSystem/IOHIPointing.cpp
	./IOHIDSystem/IOHITablet.cpp
	./IOHIDSystem/IOHITabletPointer.cpp
	./IOHIDSystem/IOHIDDeviceShim.cpp
	./IOHIDFamily/IOHIDEventServiceQueue.cpp
	./IOHIDSystem/IOHIDUserClient.cpp
	./IOHIDSystem/IOFixed64.cpp
	./IOHIDSystem/IOHIDWorkLoop.cpp
	./IOHIDSystem/IOFixedPoint64.cpp
	./IOHIDSystem/IOHIDSystemCursorHelper.cpp
	./IOHIDFamily/IOHIDResourceUserClient.cpp
	./IOHIDFamily/IOHIDResource.cpp
)

add_library(IOHIDLib STATIC
	./IOHIDLib/IOHIDIUnknown2.m
	./IOHIDLib/IOHIDTransactionClass.m
	./IOHIDLib/HIDLibElement.m
	./IOHIDLib/IOHIDIUnknown.cpp
	./IOHIDLib/IOHIDFamilyProbe.d
	./IOHIDLib/IOHIDQueueClass.mm
	./IOHIDLib/IOHIDEventServiceFastPathClass.cpp
	./IOHIDLib/IOHIDUPSClass.m
	./IOHIDLib/IOHIDLibFactory.mm
	./IOHIDLib/IOHIDDeviceClass.m
	./IOHIDLib/IOHIDObsoleteDeviceClass.m
)

add_library(HIDDriverKit STATIC
	./HIDDriverKit/HIDDriverKit_Private.iig
	./HIDDriverKit/IOHIDElementPrivate.iig
	./HIDDriverKit/IOHIDElementContainer.iig
	./HIDDriverKit/IOHIDDigitizerCollection.iig
	./HIDDriverKit/IOHIDEvent.iig
	./HIDDriverKit/IOHIDInterfaceElementContainer.iig
	./HIDDriverKit/IOUserUSBHostHIDDevice.iig
	./HIDDriverKit/HIDDriverKit.iig
	./HIDDriverKit/IOUserHIDEventService.iig
	./HIDDriverKit/IOUserHIDDevice.iig
	./HIDDriverKit/IOHIDInterface.iig
	./HIDDriverKit/IOHIDEventService.iig
	./HIDDriverKit/IOHIDElement.iig
	./HIDDriverKit/IOHIDDevice.iig
	./HIDDriverKit/IOUserHIDEventDriver.iig
	./HIDDriverKit/HIDDriverKitDebug.cpp
	./HIDDriverKit/IOHIDEventService.cpp
	./HIDDriverKit/IOUserHIDDevice.cpp
	./HIDDriverKit/IOHIDDigitizerCollection.cpp
	./HIDDriverKit/IOHIDInterface.cpp
	./HIDDriverKit/IOHIDElementContainer.cpp
	./HIDDriverKit/IOHIDDevice.cpp
	./HIDDriverKit/IOUserHIDEventDriver.cpp
	./HIDDriverKit/IOUserHIDEventService.cpp
	./HIDDriverKit/IOHIDInterfaceElementContainer.cpp
	./HIDDriverKit/IOHIDElementPrivate.cpp
	./HIDDriverKit/IOHIDEvent.cpp
	./HIDDriverKit/IOUserUSBHostHIDDevice.cpp
)

add_library(HIDDescriptorParser STATIC
	./IOHIDSystem/IOHIDDescriptorParser/PoolAlloc.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDCheckReport.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDCountDescriptorItems.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtonCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtons.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetButtonsOnPage.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetCollectionNodes.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetData.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetNextButtonInfo.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetNextUsageValueInfo.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetReportLength.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetUsageValueArray.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDGetValueCaps.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDHasUsage.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDInitReport.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDIsButtonOrValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDMaxUsageListLength.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDNextItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDOpenCloseDescriptor.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDParseDescriptor.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDPostProcessRIValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessCollection.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessGlobalItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessLocalItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessMainItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDProcessReportItem.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDPutData.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDScaleUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetButtons.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetScaledUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetUsageValue.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDSetUsageValueArray.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageAndPageFromIndex.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageInRange.c
	./IOHIDSystem/IOHIDDescriptorParser/HIDUsageListDifference.c
)
